export const PRODUCT_CONSTANT = {
    SEARCH: 'SEARCH',
    SEARCH_FILTER_PRICE: 'SEARCH_FILTER_PRICE',
    SEARCH_FILTER_NAME: 'SEARCH_FILTER_NAME',
    ADD_PRODUCT: 'ADD_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    MINUS_PRODUCT: 'MINUS_PRODUCT',
    VIEW_PRODUCT: 'VIEW_PRODUCT',
    PLUS_DETAILS: 'PLUS_DETAILS',
    MINUS_DETAILS: 'MINUS_DETAILS'
}